### ISSUE TITLE
キックオフ 2016/4/7

### ISSUE THREAD

**Issue by sotetsuk** [sotetsuk/procon-study-group#1]
# アジェンダ
- キックオフの説明
  - 会のモチベーション
  - 教科書の説明
  - 解き方の説明（各自TODO参考; 解いてプルリクをmasterに投げる。レビュー欲しければアサイン）
  - 日程（最低次回、できれば曜日）
  - 順番決め
- 本日分の解説・演習
# 目的・モチベーション
- アルゴリズム・データ構造の理解
- ホワイトボードコーディング対策

採用面接では必須（特に海外の）

> 面接ではかなりの確率で、データ構造とアルゴリズムについての質問が面接官から投げかけられます。良くも悪くも、それが真実なのです。
> 
> [プログラミング面接を突破する方法 (前編)](http://postd.cc/how-to-pass-a-programming-interview-1/)

Indeed初任給

> 初年度　約658万円～
> （2015年度実績　月給：455,521円+賞与）
> 
> [採用情報 Global Engineer（indeed）](http://r.recruit-jinji.jp/about/course/06/)
# 教科書

[プログラミングコンテスト攻略のためのアルゴリズムとデータ構造](http://www.amazon.co.jp/dp/4839952957/ref=pd_lpo_sbs_dp_ss_3?pf_rd_p=187205609&pf_rd_s=lpo-top-stripe&pf_rd_t=201&pf_rd_i=4839942390&pf_rd_m=AN1VRQENFRJN5&pf_rd_r=13KZVTWSE06JN0HF2WRE)
# 参加者
- sotetsuk (AOJ: sotetsuk, POJ: sotetsuk, AtCoder: sotetsuk)
- ryof (AOJ: ryof)
- cauchym (AOJ: cauchym)
- toiroakr(AOJ:a_Higu)
- kikunantoka (AOJ: kikunantoka, AtCoder: kikunantoka)
# 進め方
1. 毎週（2題）を担当者が解説（各20min以内程度）
2. 皆で解く（事前に問いてくるのが理想）
   - AOJの問題を通す
   - 解いた問題をmasterにプルリクを送る（レビューが欲しければ誰かにassignする、どうでも良ければ自分でマージ）
   - （slackの#procon_notificationに通知が行きます）
   - 基本的には解けたら帰る
# 問題

[ALDS1_1_D: Maximum Profit](http://judge.u-aizu.ac.jp/onlinejudge/description.jsp?id=ALDS1_1_D)
# 各自TODO
- [AOJ](http://judge.u-aizu.ac.jp/)のアカウントを作る。
- GitHubアカウント、AOJアカウントをこのスレッドに書き込む。
  - 形式: [github-account] (AOJ: [aoj-account])
  - e.g., sotetsuk (AOJ: sotetsuk, POJ: sotetsuk, AtCoder: sotetsuk)
- （余力があれば）教科書の2章まで読んでくる。
- （余力があれば）進め方 2.の解き方に沿って解いてAOJ通してプルリクを出す
  - e.g., #2 
# misc
- [x] このIssueの内容をREADMEかwikiに移す（sotetsuk）
- [x] Issueが出来たときにもnotification飛ばす

**Comment by sotetsuk** [comment]
↓な感じでアカウントを書いてくれると◎

sotetsuk (AOJ: sotetsuk)

**Comment by ryof** [comment]
ryof (AOJ: ryof)

**Comment by cauchym** [comment]
cauchym (AOJ: cauchym)
Rubyでやろうと思ってたんだけどRuntime Error多発で死にたさがあります

**Comment by sotetsuk** [comment]
@cauchym 言語はあんま関係ないはずで、REは多分本質的じゃないミスですね。プルリク上げてくれれば見ますけどね。

**Comment by cauchym** [comment]
@cauchym プルリク上げました！！ご確認おなしゃっす

**Comment by toiroakr** [comment]
toiroakr(AOJ:a_Higu)

**Comment by cauchym** [comment]
本日チームのキックオフ飲みがあるので参加できません！すんません。

結果の様子です。
http://judge.u-aizu.ac.jp/onlinejudge/review.jsp?rid=1721145#2

a_Higuさんと隣でびっくりした。
![2016-04-07 10 13 35](https://cloud.githubusercontent.com/assets/1453603/14337518/96d4cbcc-fca9-11e5-9b32-4e08c3535847.png)

**Comment by kikunantoka** [comment]
kikunantoka (AOJ: kikunantoka, AtCoder: kikunantoka)

**Comment by cauchym** [comment]
### TODO

(必要であれば)githubとslackを連携してPRやcommentsがslackで流れるようにする。sotetsuk のリポジトリだから、githubとのひも付けはsotetsukにお願いする必要がある。

### 要検討

上に付随して、個人のリポジトリをお借りするデメリットを洗い出して(なさそうだけど)
必要ならOrganizations, teamなどを作ってもよいかも、と少し思いましたが私今日行けません...すんません。

**Comment by nishimuuu** [comment]
nishimuuuuuu(AOJ: nishimuuuuuu)

**Comment by sat0yu** [comment]
sat0yu(AOJ: sat0yu)

**Comment by chiiia12** [comment]
chiiia12でおねがいします

**Comment by sotetsuk** [comment]
# 次回からの順番のループ
1. @sotetsuk
2. @nishimuuu 
3. @ryof 
4. @chiiia12 
5. @kikunantoka 
6. @toiroakr 
7. @sat0yu 

# 次回からの日程

とりあえず次回は月曜

**Comment by nsasaki128** [comment]
nsasaki128
AOJはsassanです。

**Comment by nsasaki128** [comment]
http://judge.u-aizu.ac.jp/onlinejudge/review.jsp?rid=1726244#1
